image: node:20

pipelines:
  tags:
    v*:
      - step:
          name: Build and publish to NPM
          deployement: master
          script:
            - corepack enable
            - yarn
            - yarn build
            - yarn npm publish
